name: Java CI with Maven

on:
  push:
    branches: [ "master", "junit-*" ]
  pull_request:
    branches: [ "master", "junit-*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and generate report
      run: ./mvnw -B clean site
    - name: Upload Surefire report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: target/site/
        retention-days: 14
    - name: Upload JUnit XML results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-xml-results
        path: target/surefire-reports/
        retention-days: 14
